import { ThemeProvider } from "@/app/theme-provider";
import { AppWrapper } from "../components/AppWrapper";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import "../app/globals.css";
import Head from "next/head";

export default function RootLayout({ Component, pageProps}) {
  // Use the layout defined at the page level, if available
  const queryClient = new QueryClient()
  const getLayout = Component.getLayout || ((page) => page)
  
  return getLayout(
    <ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange>
      <AppWrapper>
        <Head>
          <title>
            Champions In Christ
          </title>
        </Head>
        <main className="container">
      <QueryClientProvider client={queryClient}>
      <Component {...pageProps} />
      <ReactQueryDevtools initialIsOpen={false} />
      </QueryClientProvider>
        </main>
      </AppWrapper>
    </ThemeProvider>
  )
}



//original folder layout.tsx in app
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Champions In Christ ",
//   description: "Generated by create next app",
// };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //           >
// //         <ThemeProvider
// //             attribute="class"
// //             defaultTheme="system"
// //             enableSystem
// //             disableTransitionOnChange
// //           >
// //         {children}
// //         </ThemeProvider>
// //       </body>
// //     </html>
// //   );
// // }


// export default function RootLayout({ children }) {
//   return (
//       <html lang="en" suppressHydrationWarning>
//         <head />
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//             {children}
//         </body>
//       </html>
//   )
// }